version: '3.8'

volumes:
  mariadb:
    external: true

services:
  mariadb:
    image: mariadb
    # always restart when container is started
    restart: always
    # container name
    container_name: mariadb-container
    # set port (from:to)
    ports:
      - "3306:3306"
    environment: 
      # MongoDB Username and password
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      TZ: Asia/Seoul
    volumes:
      # -v (directory mount setting)
      - mariadb:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
