# docker compose version
version: "3"

volumes:
  mongo:
    external: true
  mongoconfig:
    external: true

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
    
services: 
  # name of the services
  mongodb:
    image: mongo
    # always restart when container is started
    restart: always
    # container name
    container_name: mongo-container
    # set port (from:to)
    ports:
      - "27017:27017"
    environment: 
      # MongoDB Username and password
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Tmd3752fuf!@
    volumes:
      # -v (directory mount setting)
      - mongo:/data/db
      - mongoconfig:/data/configdb
    networks:
      default:
        ipv4_address: 172.25.0.2

  saeroun-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: python/api:latest
    container_name: api-container
    ports:
      - "5000:5000"
    networks:
      default:
        ipv4_address: 172.25.0.3

