version: '3.8'

volumes:
  mongo:
    external: true
  mongoconfig:
    external: true

services:
  mongodb:
    image: mongo
    # always restart when container is started
    restart: always
    # container name
    container_name: mongo-container
    # set port (from:to)
    ports:
      - "27017:27017"
    environment: 
      # MongoDB Username and password
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Tmd3752fuf!@
    volumes:
      # -v (directory mount setting)
      - mongo:/data/db
      - mongoconfig:/data/configdb
